enum class CLEAR_BUFFER_BIT : int
{ COLOR   = GL_COLOR_BUFFER_BIT
, DEPTH   = GL_DEPTH_BUFFER_BIT
, ACCUM   = GL_ACCUM_BUFFER_BIT
, STENCIL = GL_STENCIL_BUFFER_BIT
, ALL = COLOR | DEPTH | ACCUM | STENCIL
};

#ifndef WRP_GLFW_NOT_UNDEF
  #undef GL_COLOR_BUFFER_BIT
  #undef GL_DEPTH_BUFFER_BIT
  #undef GL_ACCUM_BUFFER_BIT
  #undef GL_STENCIL_BUFFER_BIT
#endif

